name: Deploy to Dev
on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: dev
  IMAGE: hello

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2
      - name: Get image tag
        id: image_tag
        run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - uses: actions/setup-go@v2
      - name: Linter
        run: |
          echo "Linter is ok..."
      - name: Unit tests
        run: |
          echo "Unit tests are passed..."
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
      - name: Build and Push image to repo
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ steps.image_tag.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: svdubovik/argocd
      - name: Update api image
        run: |
          echo '"docker.pkg.github.com:${{needs.build.outputs.image_tag}}"' > image.yaml
      - name: Push changes
        run: |
          git add .
          git commit -m "From https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          git pull --rebase=true
          # git push
      - uses: act10ns/slack@v1
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_NOTIFICATIONS }}
        with:
          status: ${{ job.status }}
          channel: ${{ env.SLACK_CHANEL }}
          steps: ${{ toJson(steps) }}
